<?xml version='1.0'?>
<!-- This model is based on the robot developed by the NuBot team, this includes all the meshes -->

<robot name="tracked_vehicle" xmlns:xacro="http://www.ros.org/wiki/xacro">

  
    <gazebo>
        <self_collide>1</self_collide>
 </gazebo>
    <!-- Variables -->

    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="15" />
    <xacro:property name="track_mass" value="10" />
    <xacro:property name="flipper_mass" value="2.5" />
    <xacro:property name="track_radius" value="0.091" />
    <xacro:property name="track_width" value="0.18" />
    <xacro:property name="track_length" value="0.552" />
    <xacro:property name="track_distance" value="0.145" />
    <xacro:property name="flipper_radius" value="0.09" />
    <xacro:property name="flipper_width" value="0.038" />
    <xacro:property name="flipper_length" value="0.336" />
    <xacro:property name="flipper_distance" value="0.266" />
    <xacro:property name="flipper_visual_bias" value="0.016" />

    <!-- Variables -->


    <!-- Colours -->

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>
    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>
    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- Colours -->

    <!-- BASE LINK -->

    <link name="base_link"/>
    
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="-0.0 0 0"/>
    </joint>
    
    <!-- BASE LINK -->


    <!--chassis_link-->
    <link name='chassis_link'>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${base_mass}" />
            <inertia ixx="5" ixy="0" ixz="0"
                iyy="5" iyz="0"
                izz="5" />
        </inertial>
        
        <collision name='base_collision_1'>
            <origin xyz="${track_length/2} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="0.07" length="0.10"/>
            </geometry>
        </collision>
        
        <collision name='base_collision_2'>
            <origin xyz="${-1*track_length/2} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="0.07" length="0.10"/>
            </geometry>
        </collision>
        
        <collision name='base_collision'>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${track_length} 0.10 0.14" />
            </geometry>
        </collision>
        
        <visual name='base_visual'>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black"/>
            <geometry>
                <mesh filename="$(find tracked_robot)/description/meshes/base_link.STL" />
            </geometry>
        </visual>
    </link>
   
    <!--chassis_link-->

    <gazebo reference="chassis_link">
        <self_collide>1</self_collide>
        <mu1>1</mu1>
        <mu2>1</mu2>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <fdir1 value="0 1 0" />
        <gravity>1</gravity>
        <maxContacts>2</maxContacts>
    </gazebo>
    
    <!--left_track - LINK-->
  
    <link name='left_track_link'>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${track_mass}" />
            <inertia ixx="5" ixy="0" ixz="0"
                iyy="5" iyz="0"
                izz="5" />
        </inertial>
    
        <visual name='left_track_visual'>
            <origin xyz="0 ${-1*track_distance} 0" rpy="0 0 0" />
            <material name="blue"/>
            <geometry>
                <mesh filename="$(find tracked_robot)/description/meshes/left_track_link.STL" />
            </geometry>
        </visual>
    
        <collision name='left_track_collision_1'>
            <origin xyz="${track_length/2} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
        </collision>
    
        <collision name='left_track_collision_2'>
            <origin xyz="${-1*track_length/2} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
        </collision>
    
        <collision name='left_track_collision'>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${track_length} ${track_width} ${track_radius*2}" />
            </geometry>
        </collision>
    </link>
  
    <!--left_track - LINK-->

    <gazebo reference="left_track_link">
        <self_collide>1</self_collide>
        <mu1>10</mu1>
        <mu2>10</mu2>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <fdir1 value="0 1 0" />
        <gravity>1</gravity>
        <maxContacts>2</maxContacts>
    </gazebo>
    
    <!--left_track joints-->
  
    <joint name='left_track_joint' type='revolute'>
        <!-- fixed -->
        <origin xyz="0 ${track_distance} 0" rpy="0 0 0" />
        <child link="left_track_link" />
        <parent link="chassis_link" />
        <limit lower="-1e-16" upper="1e-16" effort="10000" velocity="10000"/>
        <!-- This cannot be zero -->
        <axis xyz="0 0 0.00001"/>
        <dynamics damping="10000" friction="10000"/>
    </joint>
    
    <!--right_track - LINK-->
   
    <link name='right_track_link'>
  
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${track_mass}" />
            <inertia ixx="5" ixy="0" ixz="0"
                iyy="5" iyz="0"
                izz="5" />
        </inertial>
    
        <visual name='right_track_visual'>
            <origin xyz="0 ${track_distance} 0" rpy="0 0 0" />
            <material name="blue"/>
            <geometry>
                <mesh filename="$(find tracked_robot)/description/meshes/right_track_link.STL" />
            </geometry>
        </visual>
    
        <collision name='right_track_collision_1'>
            <origin xyz="${track_length/2} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
        </collision>
    
        <collision name='right_track_collision_2'>
            <origin xyz="${-1*track_length/2} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${track_radius}" length="${track_width}"/>
            </geometry>
        </collision>
    
        <collision name='right_track_collision'>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${track_length} ${track_width} ${track_radius*2}" />
            </geometry>
        </collision>
    </link>
 
    <!--right_track - LINK-->

    <gazebo reference="right_track_link">
        <self_collide>1</self_collide>
        <mu1>10</mu1>
        <mu2>10</mu2>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <fdir1 value="0 1 0" />
        <gravity>1</gravity>
        <maxContacts>2</maxContacts>
    </gazebo>
    
    <!--right_track joints-->
   
    <joint name='right_track_joint' type='revolute'>
        <!-- fixed -->
        <origin xyz="0 ${-1*track_distance} 0" rpy="0 0 0" />
        <parent link="chassis_link" />
        <child link="right_track_link" />
        <limit lower="-1e-16" upper="1e-16" effort="10000" velocity="10000"/>
        <axis xyz="0 0 0.000001"/>
        <dynamics damping="10000" friction="10000"/>
    </joint>

    <!--rear_left_flipper - LINK-->
  
    <link name='rear_left_flipper_link'>
    
        <inertial>
            <origin xyz="${-1*flipper_length/2} 0 0" rpy="0 0 0" />
            <mass value="${flipper_mass}" />
            <inertia ixx="5" ixy="0" ixz="0"
                iyy="5" iyz="0"
                izz="5" />
        </inertial>
        
        <visual name='rear_left_flipper_visual'>
        
            <origin xyz="0 ${-1*flipper_visual_bias} 0" rpy="0 0 0" />
            <material name="orange"/>
            <geometry>
                <mesh filename="$(find tracked_robot)/description/meshes/back_left_fin_link.STL" />
            </geometry>
        
        </visual>

        <collision name='rear_left_flipper_collision_large_wheel_collision'>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${flipper_radius}" length="${flipper_width}"/>
            </geometry>
        </collision>
        
        <collision name='rear_left_flipper_collision_small_wheel_collision'>
        
            <origin xyz="${-1*flipper_length} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${flipper_radius}" length="${flipper_width}"/>
            </geometry>
        
        </collision>
        
        <collision name='rear_left_flipper_collision_middle_bar_collision'>
            <origin xyz="${-1*flipper_length/2} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${flipper_length} ${flipper_width} ${flipper_radius*2}" />
            </geometry>
        </collision>

    </link>
   
    <!--rear_left_flipper - LINK-->

    <gazebo reference="rear_left_flipper_link">
        
        <self_collide>1</self_collide>
        <mu1>10</mu1>
        <mu2>10</mu2>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <fdir1 value="0 1 0" />
        <gravity>1</gravity>
        <maxContacts>2</maxContacts>
        
    </gazebo>

    <joint name='rear_left_flipper_joint' type='revolute'>
        <origin xyz="${-1*track_length/2} ${flipper_distance} 0" rpy="0 0 0" />
        <child link="rear_left_flipper_link" />
        <parent link="chassis_link" />
        <axis xyz="0 1 0" />
        <limit lower="-3" upper="3" effort="1" velocity="1.0" />
    </joint>

    <!--rear_right_flipper -LINK-->
 
    <link name='rear_right_flipper_link'>
        <inertial>
            <origin xyz="${-1*flipper_length/2} 0 0" rpy="0 0 0" />
            <mass value="${flipper_mass}" />
            <inertia ixx="5" ixy="0" ixz="0"
                iyy="5" iyz="0"
                izz="5" />
        </inertial>

        <visual name='rear_right_flipper_visual'>
            <origin xyz="0 ${flipper_visual_bias} 0" rpy="0 0 0" />
            <material name="black"/>
            <geometry>
                <mesh filename="$(find tracked_robot)/description/meshes/back_right_fin_link.STL" />
            </geometry>
        </visual>

        <collision name='rear_right_flipper_collision_large_wheel_collision'>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${flipper_radius}" length="${flipper_width}"/>
            </geometry>
        </collision>
        
        <collision name='rear_right_flipper_collision_small_wheel_collision'>
            <origin xyz="${-1*flipper_length} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${flipper_radius}" length="${flipper_width}"/>
            </geometry>
        </collision>
        
        <collision name='rear_right_flipper_collision_middle_bar_collision'>
            <origin xyz="${-1*flipper_length/2} 0 0" rpy="0 0 ${PI}" />
            <geometry>
                <box size="${flipper_length} ${flipper_width} ${flipper_radius*2}" />
            </geometry>
        </collision>
    </link>
  
    <!--rear_right_flipper -LINK-->


    <gazebo reference="rear_right_flipper_link">
        <self_collide>1</self_collide>
        <mu1>10</mu1>
        <mu2>10</mu2>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <fdir1 value="0 1 0" />
        <gravity>1</gravity>
        <maxContacts>2</maxContacts>
    </gazebo>

    <joint name='rear_right_flipper_joint' type='revolute'>
        <origin xyz="${-1*track_length/2} ${-1*flipper_distance} 0" rpy="0 0 0" />
        <child link="rear_right_flipper_link" />
        <parent link="chassis_link" />
        <axis xyz="0 1 0" />
        <limit lower="-3" upper="3" effort="1" velocity="1.0" />
    </joint>

    <!--front_left_flipper -LINK-->
   
    <link name='front_left_flipper_link'>
        <inertial>
            <origin xyz="${flipper_length/2} 0 0" rpy="0 0 0" />
            <mass value="${flipper_mass}" />
            <inertia ixx="5" ixy="0" ixz="0"
                iyy="5" iyz="0"
                izz="5" />
        </inertial>

        <visual name='front_left_flipper_visual'>
            <origin xyz="0 ${-1*flipper_visual_bias} 0" rpy="0 0 0" />
            <material name="orange"/>

            <geometry>
                <mesh filename="$(find tracked_robot)/description/meshes/front_left_fin_link.STL" />
            </geometry>
        </visual>

        <collision name='front_left_flipper_collision_large_wheel_collision'>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${flipper_radius}" length="${flipper_width}"/>
            </geometry>
        </collision>
        
        <collision name='front_left_flipper_collision_small_wheel_collision'>
            <origin xyz="${flipper_length} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${flipper_radius}" length="${flipper_width}"/>
            </geometry>
        </collision>
        
        <collision name='front_left_flipper_collision_middle_bar_collision'>
            <origin xyz="${flipper_length/2} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${flipper_length} ${flipper_width} ${flipper_radius*2}" />
            </geometry>
        </collision>
    </link>
  
    <!--front_left_flipper - LINK-->



    <gazebo reference="front_left_flipper_link">
        <self_collide>1</self_collide>
        <mu1>10</mu1>
        <mu2>10</mu2>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <fdir1 value="0 1 0" />
        <gravity>1</gravity>
        <maxContacts>2</maxContacts>
    </gazebo>

    <joint name='front_left_flipper_joint' type='revolute'>
        <origin xyz="${track_length/2} ${flipper_distance} 0" rpy="0 0 0" />
        <child link="front_left_flipper_link" />
        <parent link="chassis_link" />
        <axis xyz="0 1 0" />
        <limit lower="-3" upper="3" effort="1" velocity="1.0" />
    </joint>

    <!--front_right_flipper - LINK-->
  
    <link name='front_right_flipper_link'>
        <inertial>
            <origin xyz="${flipper_length/2} 0 0" rpy="0 0 0" />
            <mass value="${flipper_mass}" />
            <inertia ixx="5" ixy="0" ixz="0"
                iyy="5" iyz="0"
                izz="5" />
        </inertial>

        <visual name='front_right_flipper_link_visual'>
            <material name="orange"/>

            <origin xyz="0 ${flipper_visual_bias} 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="$(find tracked_robot)/description/meshes/front_right_fin_link.STL" />
            </geometry>
        </visual>

        <collision name='front_right_flipper_collision_large_wheel_collision'>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${flipper_radius}" length="${flipper_width}"/>
            </geometry>
        </collision>
        
        <collision name='front_right_flipper_collision_small_wheel_collision'>
            <origin xyz="${flipper_length} 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder radius="${flipper_radius}" length="${flipper_width}"/>
            </geometry>
        </collision>
        
        <collision name='front_right_flipper_collision_middle_bar_collision'>
            <origin xyz="${flipper_length/2} 0 0" rpy="0 0 ${PI}" />
            <geometry>
                <box size="${flipper_length} ${flipper_width} ${flipper_radius*2}" />
            </geometry>
        </collision>
    </link>
   
    <!--front_right_flipper - LINK-->


    <gazebo reference="front_right_flipper_link">
        <self_collide>1</self_collide>
        <mu1>10</mu1>
        <mu2>10</mu2>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <fdir1 value="0 1 0" />
        <gravity>1</gravity>
        <maxContacts>2</maxContacts>
    </gazebo>

    <joint name='front_right_flipper_joint' type='revolute'>
        <origin xyz="${track_length/2} ${-1*flipper_distance} 0" rpy="0 0 0" />
        <child link="front_right_flipper_link" />
        <parent link="chassis_link" />
        <axis xyz="0 1 0" />
        <limit lower="-3" upper="3" effort="1" velocity="1.0" />
    </joint>



<!-- Plugins -->


    <gazebo>
        <plugin filename="libSimpleTrackedVehiclePlugin.so" name="tracked_vehicle_plugin">
            <body>base_link</body>
            <left_track>left_track_link</left_track>
            <right_track>right_track_link</right_track>
            <left_flipper>front_left_flipper_link</left_flipper>
            <left_flipper>rear_left_flipper_link</left_flipper>
            <right_flipper>front_right_flipper_link</right_flipper>
            <right_flipper>rear_right_flipper_link</right_flipper>
            <track_mu>2</track_mu>
            <track_mu2>0.5</track_mu2>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin filename="libKeysToCmdVelPlugin.so" name="keyboard_control">
            <publish_as_twist>true</publish_as_twist>
            <!-- This MUST be the name of the ros package -->
            <cmd_vel_topic>~/tracked_robot/cmd_vel_twist</cmd_vel_topic>   
        </plugin>
    </gazebo>


    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
    <joint name="front_right_flipper_joint">
        <command_interface name="position">
          <param name="min">-1</param>
          <param name="max">1</param>
        </command_interface>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

      <joint name="front_left_flipper_joint">
        <command_interface name="position">
          <param name="min">-1</param>
          <param name="max">1</param>
        </command_interface>
        <state_interface name="position"/>
      </joint>

      <joint name="rear_right_flipper_joint">
        <command_interface name="position">
          <param name="min">-1</param>
          <param name="max">1</param>
        </command_interface>
        <state_interface name="position"/>
      </joint>

      <joint name="rear_left_flipper_joint">
        <command_interface name="position">
          <param name="min">-1</param>
          <param name="max">1</param>
        </command_interface>
        <state_interface name="position"/>
      </joint>

    </ros2_control>

    <gazebo>
        <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
            <parameters>$(find tracked_robot)/config/flipper_joint.yaml</parameters>
        </plugin>   
    </gazebo>
    
    <gazebo>
        <plugin filename="libhello_world.so" name="hello_world">
        </plugin>   
    </gazebo>
</robot>